 export const countryCode = [
    { name: "India", code: 91 },
    { name: "United States", code: 1 },
    { name: "United Kingdom", code: 44 },
    { name: "Canada", code: 1 },
    { name: "Australia", code: 61 },
    { name: "Germany", code: 49 },
    { name: "France", code: 33 },
    { name: "Japan", code: 81 },
    { name: "China", code: 86 },
    { name: "Brazil", code: 55 },
    { name: "South Africa", code: 27 },
    { name: "Russia", code: 7 },
    { name: "Italy", code: 39 },
    { name: "Mexico", code: 52 },
    { name: "Spain", code: 34 },
    { name: "Netherlands", code: 31 },
    { name: "Sweden", code: 46 },
    { name: "New Zealand", code: 64 },
    { name: "South Korea", code: 82 },
    { name: "Singapore", code: 65 },
    { name: "Saudi Arabia", code: 966 },
    { name: "United Arab Emirates", code: 971 },
    { name: "Argentina", code: 54 },
    { name: "Nigeria", code: 234 },
    { name: "Indonesia", code: 62 },
    { name: "Pakistan", code: 92 },
];
