
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import ScrollToTopButton from "@/components/ScrollButton/ScrollButton";
import ReduxProvider from "@/components/ReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <Navbar/>
        <ScrollToTopButton/>
        <ReduxProvider>{children}</ReduxProvider>
        <Footer/>    
      </body>
    </html>
  );
}
